config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :number_of_guests, :price_per_night)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<%= form_for(@flat) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :number_of_guests %>
  <%= f.number_field  :number_of_guests %>
  <%= f.label :price_per_night %>
  <%= f.number_field :price_per_night %>
  <%= f.submit %>
<% end %>

app/views/flats/index.html.erb
<h1> All our flats </h1>

  <div>
    <% @flats.each do |flat| %>
      <ul>
        <li> <%= link_to flat.name, flat_path(flat) %></li>
        <li> <%= flat.address %></li>
        <div>
          <li><i class="fas fa-users"></i>
           <%= flat.number_of_guests %></li>
          <li><i class="fas fa-euro-sign"></i>
          <%=flat.price_per_night %></li>
        </div>
      </ul>
    <% end %>
  </div>

  <%= link_to "New flat", new_flat_path  %>

app/views/flats/new.html.erb
<h1> New Flat </h1>

<%= form_for(@flat) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :number_of_guests %>
  <%= f.number_field  :number_of_guests %>
  <%= f.label :price_per_night %>
  <%= f.number_field :price_per_night %>
  <%= f.submit %>

<% end %>

app/views/flats/show.html.erb
<h1> Flat detail </h1>

<%= @flat.name %> <br>
<%= @flat.address %> <br>
<%= @flat.number_of_guests %> <br>
<%= @flat.price_per_night %> <br>


<%= link_to "Back home", flats_path %> <br>
<%= link_to "Edit Flat", edit_flat_path(@flat) %> <br>
<%= link_to "Delete Flat", flat_path(@flat), method: :delete, data: { confirm: "Are u sure?" }%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>